// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Miners.Web.BusinessLayer;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Miners.Web.BusinessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505190213_AddScoreboardFields")]
    partial class AddScoreboardFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusinessLayer.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<Guid>("GuidImage")
                        .HasColumnType("uuid")
                        .HasColumnName("guid_image");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<bool>("Top")
                        .HasColumnType("boolean")
                        .HasColumnName("top");

                    b.Property<int>("UrlId")
                        .HasColumnType("integer")
                        .HasColumnName("url_id");

                    b.HasKey("Id")
                        .HasName("pk_tbl_article");

                    b.HasIndex("GuidImage")
                        .HasDatabaseName("fk_tbl_article_guid_image");

                    b.ToTable("tbl_article", "sch_miners");
                });

            modelBuilder.Entity("BusinessLayer.Entities.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<byte[]>("Data")
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("filename");

                    b.Property<int>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("size");

                    b.HasKey("Id")
                        .HasName("pk_tbl_file");

                    b.ToTable("tbl_file", "sch_miners");
                });

            modelBuilder.Entity("Miners.Web.BusinessLayer.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("code");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_tbl_category");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_tbl_category_code");

                    b.ToTable("tbl_category", "sch_miners");
                });

            modelBuilder.Entity("Miners.Web.BusinessLayer.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("integer")
                        .HasColumnName("away_score");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("away_team");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateOnly>("GameDate")
                        .HasColumnType("date")
                        .HasColumnName("game_date");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("integer")
                        .HasColumnName("home_score");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("home_team");

                    b.Property<string>("League")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("league");

                    b.HasKey("Id")
                        .HasName("pk_tbl_games");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("fk_tbl_games_category_id");

                    b.ToTable("tbl_games", "sch_miners");
                });

            modelBuilder.Entity("Miners.Web.BusinessLayer.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Email")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("email");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("bytea")
                        .HasColumnName("foto");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("jmeno");

                    b.Property<string>("Licence")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("licence");

                    b.Property<string>("PoziceTym")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pozice_tym");

                    b.Property<string>("Poznamka")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("poznamka");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("prijmeni");

                    b.Property<string>("Telefon")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("telefon");

                    b.HasKey("Id")
                        .HasName("pk_tbl_person");

                    b.ToTable("tbl_person", "sch_miners");
                });

            modelBuilder.Entity("Miners.Web.BusinessLayer.Entities.Scoreboard", b =>
                {
                    b.Property<string>("Active")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("active");

                    b.Property<string>("LiveTv")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("live_tv");

                    b.Property<string>("LiveTvUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("live_tv_url");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.ToTable("tbl_scoreboard", "sch_miners");
                });

            modelBuilder.Entity("Miners.Web.BusinessLayer.Entities.Team", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("category");

                    b.Property<string>("Coach1Function")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("coach1_function");

                    b.Property<Guid?>("Coach1Id")
                        .HasColumnType("uuid")
                        .HasColumnName("guid_coach1");

                    b.Property<string>("Coach2Function")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("coach2_function");

                    b.Property<Guid?>("Coach2Id")
                        .HasColumnType("uuid")
                        .HasColumnName("guid_coach2");

                    b.Property<string>("Coach3Function")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("coach3_function");

                    b.Property<Guid?>("Coach3Id")
                        .HasColumnType("uuid")
                        .HasColumnName("guid_coach3");

                    b.Property<string>("Coach4Function")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("coach4_function");

                    b.Property<Guid?>("Coach4Id")
                        .HasColumnType("uuid")
                        .HasColumnName("guid_coach4");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Fee")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fee");

                    b.Property<string>("League")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("league");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid?>("TeamPhoto")
                        .HasColumnType("uuid")
                        .HasColumnName("team_photo");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("TrainingDays")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("training_days");

                    b.Property<string>("TreneriKategorie")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("treneri_kategorie");

                    b.HasKey("Id")
                        .HasName("pk_tbl_team");

                    b.ToTable("tbl_team", "sch_miners");
                });

            modelBuilder.Entity("TSoft.Framework4.EfEntities.Entities.CisFrontaStav", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("Popis")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("popis");

                    b.HasKey("Id")
                        .HasName("pk_cis_fronta_stav");

                    b.ToTable("cis_fronta_stav", "sch_tsfw4");
                });

            modelBuilder.Entity("TSoft.Framework4.EfEntities.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Argument")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("argument");

                    b.Property<DateTime?>("Enddate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enddate");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error_message");

                    b.Property<string>("ErrorStack")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error_stack");

                    b.Property<Guid>("JobDefiniceId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_definice_id");

                    b.Property<DateTime?>("Queuedate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queuedate");

                    b.Property<DateTime?>("Startdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startdate");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("succeeded");

                    b.HasKey("Id")
                        .HasName("pk_tbl_job");

                    b.HasIndex("JobDefiniceId")
                        .HasDatabaseName("fk_tbl_job_job_definice_id");

                    b.ToTable("tbl_job", "sch_tsfw4");
                });

            modelBuilder.Entity("TSoft.Framework4.EfEntities.Entities.JobDefinice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("Appsettings")
                        .HasColumnType("boolean")
                        .HasColumnName("appsettings");

                    b.Property<string>("Days")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("days");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("boolean")
                        .HasColumnName("is_running");

                    b.Property<DateTime?>("LastRun")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run");

                    b.Property<bool>("LastRunOk")
                        .HasColumnType("boolean")
                        .HasColumnName("last_run_ok");

                    b.Property<bool>("LogOnlyError")
                        .HasColumnType("boolean")
                        .HasColumnName("log_only_error");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<long?>("Period")
                        .HasColumnType("bigint")
                        .HasColumnName("period");

                    b.Property<int>("Timeout")
                        .HasColumnType("integer")
                        .HasColumnName("timeout");

                    b.Property<string>("Times")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("times");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("trigger_type");

                    b.HasKey("Id")
                        .HasName("pk_tbl_job_definice");

                    b.ToTable("tbl_job_definice", "sch_tsfw4");
                });

            modelBuilder.Entity("TSoft.Framework4.EfEntities.Entities.TsfwMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("GuidTenant")
                        .HasColumnType("uuid")
                        .HasColumnName("guid_tenant");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tbl_membership");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("fk_tbl_membership_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("fk_tbl_membership_user_id");

                    b.ToTable("tbl_membership", "sch_tsfw4");
                });

            modelBuilder.Entity("TSoft.Framework4.EfEntities.Entities.TsfwRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("Global")
                        .HasColumnType("boolean")
                        .HasColumnName("global");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_tbl_role");

                    b.ToTable("tbl_role", "sch_tsfw4");
                });

            modelBuilder.Entity("TSoft.Framework4.EfEntities.Entities.TsfwUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("Application")
                        .HasColumnType("boolean")
                        .HasColumnName("application");

                    b.Property<string>("DN")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("dn");

                    b.Property<string>("DegreeAfter")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("degree_after");

                    b.Property<string>("DegreeBefore")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("degree_before");

                    b.Property<string>("Email")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("FirstName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("first_name");

                    b.Property<Guid?>("GuidTenant")
                        .HasColumnType("uuid")
                        .HasColumnName("guid_tenant");

                    b.Property<string>("LastName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_name");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("phone_number");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.HasKey("Id")
                        .HasName("pk_tbl_user");

                    b.ToTable("tbl_user", "sch_tsfw4");
                });

            modelBuilder.Entity("TSoft.Framework4.EfEntities.Entities.TsfwUserToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_tbl_user_token");

                    b.ToTable("tbl_user_token", "sch_tsfw4");
                });

            modelBuilder.Entity("BusinessLayer.Entities.Article", b =>
                {
                    b.HasOne("BusinessLayer.Entities.File", "Image")
                        .WithMany()
                        .HasForeignKey("GuidImage")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_tbl_article_guid_image");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Miners.Web.BusinessLayer.Entities.Game", b =>
                {
                    b.HasOne("Miners.Web.BusinessLayer.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_tbl_games_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TSoft.Framework4.EfEntities.Entities.Job", b =>
                {
                    b.HasOne("TSoft.Framework4.EfEntities.Entities.JobDefinice", "JobDefinice")
                        .WithMany()
                        .HasForeignKey("JobDefiniceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_tbl_job_job_definice_id");

                    b.Navigation("JobDefinice");
                });

            modelBuilder.Entity("TSoft.Framework4.EfEntities.Entities.TsfwMembership", b =>
                {
                    b.HasOne("TSoft.Framework4.EfEntities.Entities.TsfwRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_tbl_membership_role_id");

                    b.HasOne("TSoft.Framework4.EfEntities.Entities.TsfwUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_tbl_membership_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
